# Generated by Django 3.1.5 on 2021-02-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190907_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
    ]
